export const avatarColors = [
  { bg: '#F5EDD4', color: '#8A6A10' },
  { bg: '#EDE4F5', color: '#6A3A9A' },
  { bg: '#D4EDE4', color: '#1A6A4A' },
  { bg: '#F5D4D4', color: '#8A2A2A' },
  { bg: '#D4E4F5', color: '#1A4A8A' },
  { bg: '#F5EAD4', color: '#8A5A10' },
];

export const reviews = [
  { id: 1, name: "Marguerite D.", loc: "New York, NY", breed: "Golden Retriever", stars: 5, date: "April 2025", text: "The entire process was extraordinary. From first contact to the moment we brought Biscuit home, the care and transparency were unmatched." },
  { id: 2, name: "James & Fiona T.", loc: "Austin, TX", breed: "Cavapoo", stars: 5, date: "March 2025", text: "We searched for a responsible breeder for over a year. The level of detail in the health documentation was everything we hoped for." },
  { id: 3, name: "Oliver K.", loc: "Miami, FL", breed: "French Bulldog", stars: 5, date: "March 2025", text: "Absolutely first-class experience. The flight nanny service was seamless and our little Luna arrived happy and healthy." },
  { id: 4, name: "Natalie R.", loc: "Los Angeles, CA", breed: "Goldendoodle", stars: 5, date: "February 2025", text: "Signature Companions truly sets the gold standard. Our puppy is not only beautiful but has the calmest temperament we've ever seen." },
  { id: 5, name: "Samuel N.", loc: "Chicago, IL", breed: "Golden Retriever", stars: 4, date: "February 2025", text: "High-quality breeding. Communication was great, though the waiting list was long—but now I understand why. She's perfect." },
  { id: 6, name: "Charlotte S.", loc: "Seattle, WA", breed: "Cavapoo", stars: 5, date: "January 2025", text: "The weekly photo updates made the waiting process so special. Our Teddy is the star of the neighborhood!" },
  { id: 7, name: "Marcus J.", loc: "Denver, CO", breed: "French Bulldog", stars: 5, date: "January 2025", text: "Expertly socialized. Bruno adjusted to our home within the first 24 hours. You can tell these dogs are raised with love." },
  { id: 8, name: "Isabella W.", loc: "Boston, MA", breed: "Goldendoodle", stars: 5, date: "December 2024", text: "A truly luxury experience. They matched us with a puppy that fits our lifestyle perfectly. Highly recommend to serious owners." },
  { id: 9, name: "David & Claire H.", loc: "Nashville, TN", breed: "Golden Retriever", stars: 5, date: "December 2024", text: "The health guarantees and pedigree documentation gave us total peace of mind. Exceptional ethics and professionalism." },
  { id: 10, name: "Sophia N.", loc: "San Francisco, CA", breed: "Cavapoo", stars: 5, date: "November 2024", text: "Signature Companions is simply the best. Our girl is highly intelligent and was incredibly easy to crate train." },
  { id: 11, name: "Michael T.", loc: "Phoenix, AZ", breed: "French Bulldog", stars: 5, date: "November 2024", text: "The most thorough adoption experience we've ever had. No detail was overlooked, from the starter kit to the travel arrangements." },
  { id: 12, name: "Emma & Paul F.", loc: "Atlanta, GA", breed: "Golden Retriever", stars: 4, date: "October 2024", text: "Beautiful, healthy pup. The transition was smooth and the post-adoption support team has been very responsive to our questions." },
  { id: 13, name: "Kieran B.", loc: "Portland, OR", breed: "Goldendoodle", stars: 5, date: "October 2024", text: "You get what you pay for: excellence. The genetic testing provided was more extensive than any other breeder we interviewed." },
  { id: 14, name: "Luisa G.", loc: "San Diego, CA", breed: "Cavapoo", stars: 5, date: "September 2024", text: "Our family is complete. Thank you for the care you put into these puppies. Daisy is gentle, playful, and so sweet." },
  { id: 15, name: "Andreas K.", loc: "Philadelphia, PA", breed: "French Bulldog", stars: 5, date: "September 2024", text: "Top-tier service. The temperament matching process was spot on. Our boy is the perfect addition to our city apartment." },
  { id: 16, name: "Priya S.", loc: "Charlotte, NC", breed: "Golden Retriever", stars: 5, date: "August 2024", text: "Extremely professional. The facility is immaculate and the dogs are clearly cherished. This is how breeding should be done." },
  { id: 17, name: "Henrik M.", loc: "Minneapolis, MN", breed: "Goldendoodle", stars: 5, date: "August 2024", text: "We traveled from out of state to collect our pup and it was worth every mile. A benchmark for ethical breeding." },
  { id: 18, name: "Amelia C.", loc: "Las Vegas, NV", breed: "Cavapoo", stars: 5, date: "July 2024", text: "From the first inquiry to the day we met our pup, the communication was flawless. Thank you for everything!" },
  { id: 19, name: "Rafael A.", loc: "Dallas, TX", breed: "Golden Retriever", stars: 5, date: "July 2024", text: "Stunning dogs and wonderful people. Our Golden is the healthiest, most athletic dog we've ever owned." },
  { id: 20, name: "Isabel R.", loc: "Salt Lake City, UT", breed: "French Bulldog", stars: 4, date: "June 2024", text: "Very happy with our new family member. Healthy, happy, and already partially potty trained when he arrived." },
  { id: 21, name: "Daniel H.", loc: "Charleston, SC", breed: "Goldendoodle", stars: 5, date: "June 2024", text: "Professionalism, integrity, and elegance. Signature Companions delivers on every promise they make." },
  { id: 22, name: "Mila J.", loc: "Aspen, CO", breed: "Cavapoo", stars: 5, date: "May 2024", text: "The personalized updates made us feel like part of the family before we even picked up our puppy. Exceptional service." },
  { id: 23, name: "Yuki T.", loc: "Honolulu, HI", breed: "Golden Retriever", stars: 5, date: "May 2024", text: "They handled the complex island logistics perfectly. Our puppy arrived calm and ready for the beach!" },
  { id: 24, name: "George P.", loc: "Savannah, GA", breed: "French Bulldog", stars: 5, date: "April 2024", text: "Flawless genetics and beautiful coat. We have recommended Signature Pets to all our friends." },
  { id: 25, name: "Nadia P.", loc: "Boulder, CO", breed: "Goldendoodle", stars: 5, date: "April 2024", text: "An ethical breeder that truly cares about the long-term health of their lines. We couldn't be more pleased." },
  { id: 26, name: "Christopher B.", loc: "Washington, D.C.", breed: "Golden Retriever", stars: 5, date: "March 2024", text: "The temperament profile they sent was incredibly accurate. Our boy is exactly as described—loyal and gentle." },
  { id: 27, name: "Finn H.", loc: "Newport, RI", breed: "Cavapoo", stars: 5, date: "March 2024", text: "Luxury breeding at its finest. The support we've received post-adoption has been invaluable for our first pup." },
  { id: 28, name: "Valentina C.", loc: "Santa Fe, NM", breed: "French Bulldog", stars: 5, date: "February 2024", text: "Such a beautiful experience. Luna is a healthy, vibrant, and joyful little soul. Thank you for our best friend." },
  { id: 29, name: "Patrick V.", loc: "New Orleans, LA", breed: "Golden Retriever", stars: 5, date: "February 2024", text: "A benchmark for quality. Transparent, honest, and deeply passionate about their craft. Five stars aren't enough." },
  { id: 30, name: "Anna-Lena S.", loc: "Palm Springs, CA", breed: "Goldendoodle", stars: 4, date: "January 2024", text: "Great experience overall. The puppy starter kit was very thoughtful and helped us settle in quickly." }
];